#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# 7.4.0
PHP_VERSION="${1}"
# 7.4
PHP_MAJOR=$(echo ${PHP_VERSION} | cut -d . -f -2)

if [[ -z "${PHP_VERSION// }" ]]; then
    cat << EOF
Usage: build PHP_VERSION
Builds CLI, FPM, Apache and Nginx images for PHP PHP_VERSION

Example: build 7.4.0
    Builds these images - jtreminio:php-cli
                        - jtreminio:php
                        - jtreminio:php-apache
                        - jtreminio:php-nginx
EOF
fi

if [[ ${PHP_VERSION} != "env" ]] && [[ "${PHP_VERSION// }" == "${PHP_MAJOR// }" ]]; then
    printf "PHP_VERSION must be in 7.4.0 format"
    exit 1
fi

REGEXP="([0-9]{1}\.)+([0-9]{1}\.)+([0-9]{1,2})"
if [[ ${PHP_VERSION} != "env" ]] && ! [[ ${PHP_VERSION} =~ ${REGEXP} ]]; then
    printf "PHP_VERSION must be in 7.4.0 format"
    exit 1
fi

IS_LATEST=0
if [[ ${PHP_MAJOR} == 7.4 ]]; then
    IS_LATEST=1
fi

function main() {
    if [[ PHP_VERSION == "env" ]]; then
        build_env_image

        docker image push jtreminio/phpenv:latest
        exit 0
    fi

    build_php_cli_image ${PHP_MAJOR} ${PHP_VERSION}
    build_php_fpm_image ${PHP_MAJOR} ${PHP_VERSION}
    build_apache_image ${PHP_MAJOR} ${PHP_VERSION}
    build_nginx_image ${PHP_MAJOR} ${PHP_VERSION}

    bash "${DIR}/test" ${PHP_VERSION}

    if [[ $? -ne 0 ]]; then
        exit 1
    fi

    docker image push jtreminio/php-cli:${PHP_MAJOR}
    docker image push jtreminio/php-cli:${PHP_VERSION}
    docker image push jtreminio/php:${PHP_MAJOR}
    docker image push jtreminio/php:${PHP_VERSION}
    docker image push jtreminio/php-apache:${PHP_MAJOR}
    docker image push jtreminio/php-apache:${PHP_VERSION}
    docker image push jtreminio/php-nginx:${PHP_MAJOR}
    docker image push jtreminio/php-nginx:${PHP_VERSION}

    if [[ ${IS_LATEST} -eq 1 ]]; then
        docker image push jtreminio/php-cli:latest
        docker image push jtreminio/php:latest
        docker image push jtreminio/php-apache:latest
        docker image push jtreminio/php-nginx:latest
    fi

    cat << EOF
        The following images were built and pushed:

        jtreminio/php-cli:${PHP_MAJOR}
        jtreminio/php-cli:${PHP_VERSION}
        jtreminio/php:${PHP_MAJOR}
        jtreminio/php:${PHP_VERSION}
        jtreminio/php-apache:${PHP_MAJOR}
        jtreminio/php-apache:${PHP_VERSION}
        jtreminio/php-nginx:${PHP_MAJOR}
        jtreminio/php-nginx:${PHP_VERSION}
EOF

    if [[ ${IS_LATEST} -eq 1 ]]; then
        cat << EOF
        docker image push jtreminio/php-cli:latest
        docker image push jtreminio/php:latest
        docker image push jtreminio/php-apache:latest
        docker image push jtreminio/php-nginx:latest
EOF
    fi
}

function build_env_image() {
    echo "Building ENV"
    docker image build \
      -t jtreminio/env:latest \
      -f Dockerfile-env \
      .

    if [[ $? -ne 0 ]]; then
        echo "Error encountered"
        exit 1
    fi
}

function build_php_cli_image() {
    PHP_MAJOR="${1}"
    PHP_MINOR="${2}"

    LATEST_TAG=""
    if [[ ${IS_LATEST} -eq 1 ]]; then
        LATEST_TAG="-t jtreminio/php-cli:latest"
    fi

    echo "Building PHP-CLI ${PHP_MINOR}"
    docker image build \
      --build-arg PHP_VER=${PHP_MAJOR} \
      --build-arg PHP_VER_DOT=${PHP_MINOR} \
      -t jtreminio/php-cli:${PHP_MAJOR} \
      -t jtreminio/php-cli:${PHP_MINOR} \
      ${LATEST_TAG} \
      -f Dockerfile-php-cli \
      .

    if [[ $? -ne 0 ]]; then
        echo "Error encountered"
        exit 1
    fi
}

function build_php_fpm_image() {
    PHP_MAJOR="${1}"
    PHP_MINOR="${2}"

    LATEST_TAG=""
    if [[ ${IS_LATEST} -eq 1 ]]; then
        LATEST_TAG="-t jtreminio/php:latest"
    fi

    echo "Building PHP-CLI + PHP-FPM ${PHP_MINOR}"
    docker image build \
      --build-arg PHP_VER=${PHP_MAJOR} \
      --build-arg PHP_VER_DOT=${PHP_MINOR} \
      -t jtreminio/php:${PHP_MAJOR} \
      -t jtreminio/php:${PHP_MINOR} \
      ${LATEST_TAG} \
      -f Dockerfile-php-fpm \
      .

    if [[ $? -ne 0 ]]; then
        echo "Error encountered"
        exit 1
    fi
}

function build_apache_image() {
    PHP_MAJOR="${1}"
    PHP_MINOR="${2}"

    LATEST_TAG=""
    if [[ ${IS_LATEST} -eq 1 ]]; then
        LATEST_TAG="-t jtreminio/php-apache:latest"
    fi

    echo "Building PHP ${PHP_MAJOR} + Apache"
    docker image build \
      --build-arg PHP_VER_DOT=${PHP_MINOR} \
      -t jtreminio/php-apache:${PHP_MAJOR} \
      -t jtreminio/php-apache:${PHP_MINOR} \
      ${LATEST_TAG} \
      -f Dockerfile-apache \
      .

    if [[ $? -ne 0 ]]; then
        echo "Error encountered"
        exit 1
    fi
}

function build_nginx_image() {
    PHP_MAJOR="${1}"
    PHP_MINOR="${2}"

    LATEST_TAG=""
    if [[ ${IS_LATEST} -eq 1 ]]; then
        LATEST_TAG="-t jtreminio/php-nginx:latest"
    fi

    echo "Building PHP ${PHP_MAJOR} + Nginx"
    docker image build \
      --build-arg PHP_VER_DOT=${PHP_MINOR} \
      -t jtreminio/php-nginx:${PHP_MAJOR} \
      -t jtreminio/php-nginx:${PHP_MINOR} \
      ${LATEST_TAG} \
      -f Dockerfile-nginx \
      .

    if [[ $? -ne 0 ]]; then
        echo "Error encountered"
        exit 1
    fi
}

main
