#!/bin/bash
set -e
set -o pipefail

docker image build \
  -t jtreminio/php:7.3 \
  -t jtreminio/php:7.3.0-alpha4 \
  php7.3

docker image build \
  -t jtreminio/php:7.2 \
  -t jtreminio/php:7.2.8 \
  -t jtreminio/php:latest \
  -f Dockerfile-7.2 \
  .

docker image build \
  -t jtreminio/php:7.1 \
  -t jtreminio/php:7.1.20 \
  php7.1

docker image build \
  -t jtreminio/php:7.0 \
  -t jtreminio/php:7.0.31 \
  php7.0

docker image build \
  -t jtreminio/php:5.6 \
  -t jtreminio/php:5.6.37 \
  php5.6
