FROM jtreminio/phpenv:latest
LABEL maintainer="Juan Treminio <jtreminio@gmail.com>"

ENV DEBIAN_FRONTEND noninteractive
ENV APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=DontWarn

COPY files/ondrej.pgp /root/ondrej.pgp

# install base requirements
RUN apt-get update &&\
    apt-get install --no-install-recommends --no-install-suggests -y \
        ca-certificates\
        curl \
        git \
        gnupg \
        libfcgi0ldbl \
        libfcgi-bin \
        unzip \
        zip \
        &&\
    cat /root/ondrej.pgp | apt-key add &&\
        printf "deb [arch=amd64] http://ppa.launchpad.net/ondrej/php/ubuntu bionic main\n" \
>/etc/apt/sources.list.d/ondrej.list &&\
    rm -f /root/ondrej.pgp &&\
    apt-get update &&\
    apt-get -y --purge autoremove &&\
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \
           /usr/lib/x86_64-linux-gnu/perl /usr/share/perl \
           /usr/lib/x86_64-linux-gnu/libperl.* /usr/share/{man,doc}

ENV COMPOSER_HOME /.composer
ENV PHP_VER 7.2
ARG PHP_VER_DOT
ENV PHP_LIB_DIR 20170718

# Deletable dupe module directories not required by this version
ENV DEL_LIB_PHP_DIR /usr/lib/php/20131226 \
                    /usr/lib/php/20151012 \
                    /usr/lib/php/20160303 \
                    /usr/lib/php/${PHP_VER}
# Deletable extra directories that may be created by installing PHP modules
ENV DEL_PHP_DIR /etc/php/5.6 \
                /etc/php/7.0 \
                /etc/php/7.1 \
                /etc/php/7.3

# Most common PHP modules, and Composer
RUN apt-get update &&\
    apt-get -y install --no-install-recommends --no-install-suggests \
        php${PHP_VER}-amqp \
        php${PHP_VER}-apcu \
        php${PHP_VER}-bcmath \
        php${PHP_VER}-cli \
        php${PHP_VER}-curl \
        php${PHP_VER}-fpm \
        php${PHP_VER}-geoip \
        php${PHP_VER}-gnupg \
        php${PHP_VER}-igbinary \
        php${PHP_VER}-imagick \
        php${PHP_VER}-intl \
        php${PHP_VER}-json \
        php${PHP_VER}-lua \
        php${PHP_VER}-mailparse \
        php${PHP_VER}-mbstring \
        php${PHP_VER}-memcached \
        php${PHP_VER}-mongodb \
        php${PHP_VER}-mysql \
        php${PHP_VER}-oauth \
        php${PHP_VER}-opcache \
        php${PHP_VER}-radius \
        php${PHP_VER}-raphf \
        php${PHP_VER}-redis \
        php${PHP_VER}-solr \
        php${PHP_VER}-sqlite3 \
        php${PHP_VER}-ssh2 \
        php${PHP_VER}-stomp \
        php${PHP_VER}-uploadprogress \
        php${PHP_VER}-uuid \
        php${PHP_VER}-xml \
        php${PHP_VER}-zip \
        php${PHP_VER}-zmq \
        php-pear \
        php-xdebug &&\
    apt-get -y --purge autoremove &&\
    rm -rf /tmp/* \
           /var/tmp/* \
           /var/lib/apt/lists/* \
           /usr/lib/x86_64-linux-gnu/perl \
           /usr/share/perl \
           /usr/lib/x86_64-linux-gnu/libperl.* \
           /usr/share/{man,doc}

# Delete directories belonging to other PHP versions
RUN rm -rf ${DEL_LIB_PHP_DIR} \
           ${DEL_PHP_DIR}

# Install Composer
RUN install -d -m 0755 -o www-data -g www-data /.composer &&\
    curl -sS https://getcomposer.org/installer | \
        php -- --install-dir=/usr/local/bin \
               --filename=composer &&\
    chown -R www-data:www-data /.composer

# Save INI and FPM conf files into non-versioned directory
# This makes managing them across several different PHP versions easier
ADD --chown=www-data:www-data files/php.ini  /etc/php/php.ini
ADD --chown=www-data:www-data files/fpm.conf /etc/php/fpm.conf

# Use the following to mount your custom INI files as Volumes
ADD --chown=www-data:www-data files/blank.ini /etc/php/cli-custom.ini
ADD --chown=www-data:www-data files/blank.ini /etc/php/php-custom.ini

# Set up PID and sessions directories
RUN install -d -m 0755 -o www-data -g www-data /var/run/php-fpm &&\
    install -d -m 0755 -o www-data -g www-data /var/lib/php/sessions

# Inject our default INI and conf files.
# To add your own files, add to the cli or fpm conf.d directories. All INI are
# auto-loaded from this directory, and are loaded in alphabetical order. Suggested
# to start with "99-" to ensure your settings are loaded last and take precedence.
RUN rm -f /etc/php/${PHP_VER}/fpm/php-fpm.conf &&\
    ln -s /etc/php/${PHP_VER}/fpm/conf.d /etc/php/fpm-conf.d &&\
    ln -s /etc/php/${PHP_VER}/cli/conf.d /etc/php/cli-conf.d &&\
    \
    ln -s /etc/php/php.ini        /etc/php/${PHP_VER}/cli/conf.d/98-env.ini &&\
    ln -s /etc/php/php.ini        /etc/php/${PHP_VER}/fpm/conf.d/98-env.ini &&\
    ln -s /etc/php/fpm.conf       /etc/php/${PHP_VER}/fpm/php-fpm.conf &&\
    ln -s /etc/php/cli-custom.ini /etc/php/${PHP_VER}/cli/conf.d/99-custom.ini &&\
    ln -s /etc/php/php-custom.ini /etc/php/${PHP_VER}/fpm/conf.d/99-custom.ini

# Xdebug is disabled by default,
# use `-e PHP_INI_SCAN_DIR=:/etc/php/xdebug-conf.d` to enable
# Below removes symlink and creates empty file
RUN rm -f /etc/php/${PHP_VER}/cli/conf.d/20-xdebug.ini \
          /etc/php/${PHP_VER}/fpm/conf.d/20-xdebug.ini &&\
    touch /etc/php/${PHP_VER}/cli/conf.d/20-xdebug.ini \
          /etc/php/${PHP_VER}/fpm/conf.d/20-xdebug.ini &&\
    install -d -m 0755 -o www-data -g www-data /etc/php/xdebug-conf.d &&\
    mv /etc/php/${PHP_VER}/mods-available/xdebug.ini /etc/php/xdebug-conf.d/xdebug.ini

# Standardize PHP-FPM executable location
RUN rm -f /usr/sbin/php-fpm &&\
    ln -s /usr/sbin/php-fpm${PHP_VER} /usr/sbin/php-fpm

# Only set PHP_INI_SCAN_DIR inside following file so it does not affect PHP CLI
COPY files/php-fpm /usr/bin/php-fpm
# Xdebug CLI debugging
COPY files/xdebug  /usr/bin/xdebug

RUN chmod +x /usr/bin/php-fpm &&\
    chmod +x /usr/bin/xdebug

WORKDIR /etc/php/${PHP_VER}

EXPOSE 9000

CMD /usr/bin/php-fpm
