FROM phusion/baseimage:0.11

ENV PHP__allow_url_fopen=1 \
    PHP__allow_url_include= \
    PHP__always_populate_raw_post_data= \
    PHP__asp_tags= \
    PHP__auto_append_file= \
    PHP__auto_detect_line_endings=0 \
    PHP__auto_globals_jit=1 \
    PHP__auto_prepend_file= \
    PHP__browscap= \
    PHP__child_terminate= \
    PHP__default_charset=UTF-8 \
    PHP__default_mimetype=text/html \
    PHP__default_socket_timeout=60 \
    PHP__disable_classes= \
    PHP__disable_functions= \
    PHP__display_errors=Off \
    PHP__display_startup_errors= \
    PHP__docref_ext= \
    PHP__docref_root= \
    PHP__doc_root= \
    PHP__error_append_string= \
    PHP__error_log= \
    PHP__error_prepend_string= \
    PHP__error_reporting=0 \
    PHP__exit_on_timeout= \
    PHP__expose_php=1 \
    PHP__file_uploads=1 \
    PHP__html_errors=0 \
    PHP__ignore_repeated_errors= \
    PHP__ignore_repeated_source= \
    PHP__ignore_user_abort=0 \
    PHP__implicit_flush=1 \
    PHP__include_path=.:/usr/share/php \
    PHP__last_modified= \
    PHP__log_errors=1 \
    PHP__log_errors_max_len=1024 \
    PHP__max_execution_time=0 \
    PHP__max_input_nesting_level=64 \
    PHP__max_input_vars=1000 \
    PHP__max_input_time=-1 \
    PHP__memory_limit=-1 \
    PHP__open_basedir= \
    PHP__output_buffering=0 \
    PHP__output_handler= \
    PHP__enable_post_data_reading=1 \
    PHP__post_max_size=8M \
    PHP__precision=14 \
    PHP__realpath_cache_size=4096K \
    PHP__realpath_cache_ttl=120 \
    PHP__register_argc_argv=1 \
    PHP__report_memleaks=1 \
    PHP__report_zend_debug=0 \
    PHP__request_order=GP \
    PHP__sendmail_from= \
    PHP__sendmail_path="/usr/sbin/sendmail -t -i" \
    PHP__serialize_precision=-1 \
    PHP__short_open_tag= \
    PHP__SMTP=localhost \
    PHP__smtp_port=25 \
    PHP__track_errors=0 \
    PHP__unserialize_callback_func= \
    PHP__upload_max_filesize=2M \
    PHP__max_file_uploads=20 \
    PHP__upload_tmp_dir= \
    PHP__user_agent= \
    PHP__user_dir= \
    PHP__variables_order=GPCS \
    PHP__windows_show_crt_warning= \
    PHP__xbithack= \
    PHP__xmlrpc_errors=0 \
    PHP__xmlrpc_error_number=0 \
    \
    PHP__apc__cache_by_default= \
    PHP__apc__enabled= \
    PHP__apc__enable_cli= \
    PHP__apc__file_update_protection= \
    PHP__apc__filters= \
    PHP__apc__gc_ttl= \
    PHP__apc__include_once_override= \
    PHP__apc__localcache= \
    PHP__apc__localcache__size= \
    PHP__apc__max_file_size= \
    PHP__apc__mmap_file_mask= \
    PHP__apc__num_files_hint= \
    PHP__apc__report_autofilter= \
    PHP__apc__rfc1867= \
    PHP__apc__rfc1867_freq=0 \
    PHP__apc__rfc1867_name= \
    PHP__apc__rfc1867_prefix= \
    PHP__apc__shm_segments=1 \
    PHP__apc__shm_size= \
    PHP__apc__slam_defense= \
    PHP__apc__stat= \
    PHP__apc__stat_ctime= \
    PHP__apc__ttl= \
    PHP__apc__user_entries_hint= \
    PHP__apc__user_ttl= \
    PHP__apc__write_lock= \
    \
    PHP__apd__dumpdir= \
    PHP__apd__statement_tracing= \
    \
    PHP__arg_separator__input=& \
    PHP__arg_separator__output=& \
    \
    PHP__assert__active=1 \
    PHP__assert__bail=0 \
    PHP__assert__callback= \
    PHP__assert__quiet_eval=0 \
    PHP__assert__warning=1 \
    \
    PHP__axis2__client_home= \
    PHP__axis2__enable_exception= \
    PHP__axis2__enable_trace= \
    PHP__axis2__log_path= \
    \
    PHP__bcmath__scale=0 \
    \
    PHP__bcompiler__enabled= \
    \
    PHP__birdstep__max_links= \
    \
    PHP__blenc__key_file= \
    \
    PHP__cgi__check_shebang_line= \
    PHP__cgi__discard_path= \
    PHP__cgi__fix_pathinfo= \
    PHP__cgi__force_redirect= \
    PHP__cgi__nph= \
    PHP__cgi__redirect_status_env= \
    PHP__cgi__rfc2616_headers= \
    \
    PHP__cli__pager= \
    PHP__cli__prompt="\b \>" \
    PHP__cli_server__color= \
    \
    PHP__coin_acceptor__auto_initialize= \
    PHP__coin_acceptor__auto_reset= \
    PHP__coin_acceptor__command_function= \
    PHP__coin_acceptor__delay_coins= \
    PHP__coin_acceptor__delay_prom= \
    PHP__coin_acceptor__lock_on_close= \
    PHP__coin_acceptor__start_unlocked= \
    \
    PHP__com__allow_dcom= \
    PHP__com__autoregister_casesensitive= \
    PHP__com__autoregister_typelib= \
    PHP__com__autoregister_verbose= \
    PHP__com__code_page= \
    PHP__com__typelib_file= \
    \
    PHP__curl__cainfo= \
    \
    PHP__daffodildb__default_host= \
    PHP__daffodildb__default_password= \
    PHP__daffodildb__default_socket= \
    PHP__daffodildb__default_user= \
    PHP__daffodildb__port= \
    \
    PHP__date__default_latitude=31.7667 \
    PHP__date__default_longitude=35.2333 \
    PHP__date__sunrise_zenith=90.583333 \
    PHP__date__sunset_zenith=90.583333 \
    PHP__date__timezone=UTC \
    \
    PHP__dba__default_handler= \
    \
    PHP__etpan__default__charset= \
    PHP__etpan__default__protocol= \
    \
    PHP__exif__decode_jis_intel=JIS \
    PHP__exif__decode_jis_motorola=JIS \
    PHP__exif__decode_unicode_intel=UCS-2LE \
    PHP__exif__decode_unicode_motorola=UCS-2BE \
    PHP__exif__encode_jis= \
    PHP__exif__encode_unicode=ISO-8859-15 \
    \
    PHP__expect__logfile= \
    PHP__expect__loguser= \
    PHP__expect__timeout= \
    \
    PHP__fastcgi__impersonate= \
    PHP__fastcgi__logging= \
    \
    PHP__fbsql__allow_persistent= \
    PHP__fbsql__autocommit= \
    PHP__fbsql__batchsize= \
    PHP__fbsql__default_database= \
    PHP__fbsql__default_database_password= \
    PHP__fbsql__default_host= \
    PHP__fbsql__default_password= \
    PHP__fbsql__default_user= \
    PHP__fbsql__generate_warnings= \
    PHP__fbsql__max_connections= \
    PHP__fbsql__max_links= \
    PHP__fbsql__max_persistent= \
    PHP__fbsql__max_results= \
    PHP__fbsql__show_timestamp_decimals= \
    \
    PHP__filter__default=unsafe_raw \
    PHP__filter__default_flags= \
    \
    PHP__gd__jpeg_ignore_warning= \
    \
    PHP__geoip__custom_directory= \
    \
    PHP__hidef__ini_path= \
    \
    PHP__highlight__comment="#FF8000" \
    PHP__highlight__default="#0000BB" \
    PHP__highlight__html="#000000" \
    PHP__highlight__keyword="#007700" \
    PHP__highlight__string="#DD0000" \
    \
    PHP__htscanner__config_file= \
    PHP__htscanner__default_docroot= \
    PHP__htscanner__default_ttl= \
    PHP__htscanner__stop_on_error= \
    \
    PHP__http__etag__mode= \
    PHP__http__force_exit= \
    PHP__http__log__allowed_methods= \
    PHP__http__log__cache= \
    PHP__http__log__composite= \
    PHP__http__log__not_found= \
    PHP__http__log__redirect= \
    PHP__http__only_exceptions= \
    PHP__http__persistent__handles__ident= \
    PHP__http__persistent__handles__limit= \
    PHP__http__request__datashare__connect= \
    PHP__http__request__datashare__cookie= \
    PHP__http__request__datashare__dns= \
    PHP__http__request__datashare__ssl= \
    PHP__http__request__methods__allowed= \
    PHP__http__request__methods__custom= \
    PHP__http__send__deflate__start_auto= \
    PHP__http__send__deflate__start_flags= \
    PHP__http__send__inflate__start_auto= \
    PHP__http__send__inflate__start_flags= \
    PHP__http__send__not_found_404= \
    \
    PHP__ibase__allow_persistent= \
    PHP__ibase__dateformat= \
    PHP__ibase__default_charset= \
    PHP__ibase__default_db= \
    PHP__ibase__default_password= \
    PHP__ibase__default_user= \
    PHP__ibase__max_links= \
    PHP__ibase__max_persistent= \
    PHP__ibase__timeformat= \
    PHP__ibase__timestampformat= \
    \
    PHP__ibm_db2__binmode= \
    PHP__ibm_db2__i5_all_pconnect= \
    PHP__ibm_db2__i5_allow_commit= \
    PHP__ibm_db2__i5_dbcs_alloc= \
    PHP__ibm_db2__instance_name= \
    PHP__ibm_db2__i5_ignore_userid= \
    \
    PHP__iconv__input_encoding= \
    PHP__iconv__internal_encoding= \
    PHP__iconv__output_encoding= \
    \
    PHP__imlib2__font_cache_max_size= \
    PHP__imlib2__font_path= \
    \
    PHP__ingres__allow_persistent= \
    PHP__ingres__array_index_start= \
    PHP__ingres__auto= \
    PHP__ingres__blob_segment_length= \
    PHP__ingres__cursor_mode= \
    PHP__ingres__default_database= \
    PHP__ingres__default_password= \
    PHP__ingres__default_user= \
    PHP__ingres__describe= \
    PHP__ingres__fetch_buffer_size= \
    PHP__ingres__max_links= \
    PHP__ingres__max_persistent= \
    PHP__ingres__reuse_connection= \
    PHP__ingres__scrollable= \
    PHP__ingres__trace= \
    PHP__ingres__trace_connect= \
    PHP__ingres__utf8= \
    \
    PHP__ldap__max_links= \
    \
    PHP__mail__add_x_header= \
    PHP__mail__force_extra_parameters= \
    PHP__mail__log= \
    \
    PHP__maxdb__default_db= \
    PHP__maxdb__default_host= \
    PHP__maxdb__default_pw= \
    PHP__maxdb__default_user= \
    PHP__maxdb__long_readlen= \
    \
    PHP__mbstring__detect_order= \
    PHP__mbstring__encoding_translation=0 \
    PHP__mbstring__func_overload=0 \
    PHP__mbstring__http_input= \
    PHP__mbstring__http_output= \
    PHP__mbstring__internal_encoding= \
    PHP__mbstring__language=neutral \
    PHP__mbstring__script_encoding= \
    PHP__mbstring__strict_detection=0 \
    PHP__mbstring__substitute_character= \
    \
    PHP__mcrypt__algorithms_dir= \
    PHP__mcrypt__modes_dir= \
    \
    PHP__memcache__allow_failover= \
    PHP__memcache__chunk_size= \
    PHP__memcache__default_port= \
    PHP__memcache__hash_function= \
    PHP__memcache__hash_strategy= \
    PHP__memcache__max_failover_attempts= \
    \
    PHP__mime_magic__debug= \
    PHP__mime_magic__magicfile= \
    \
    PHP__mongo__allow_empty_keys= \
    PHP__mongo__chunk_size= \
    PHP__mongo__cmd= \
    PHP__mongo__default_host= \
    PHP__mongo__default_port= \
    PHP__mongo__is_master_interval= \
    PHP__mongo__long_as_object= \
    PHP__mongo__native_long= \
    PHP__mongo__ping_interval= \
    PHP__mongo__utf8= \
    \
    PHP__msql__allow_persistent= \
    PHP__msql__max_links= \
    PHP__msql__max_persistent= \
    \
    PHP__mssql__allow_persistent= \
    PHP__mssql__batchsize= \
    PHP__mssql__charset= \
    PHP__mssql__compatability_mode= \
    PHP__mssql__connect_timeout= \
    PHP__mssql__datetimeconvert= \
    PHP__mssql__max_links= \
    PHP__mssql__max_persistent= \
    PHP__mssql__max_procs= \
    PHP__mssql__min_error_severity= \
    PHP__mssql__min_message_severity= \
    PHP__mssql__secure_connection= \
    PHP__mssql__textlimit= \
    PHP__mssql__textsize= \
    PHP__mssql__timeout= \
    \
    PHP__mysql__allow_local_infile= \
    PHP__mysql__allow_persistent= \
    PHP__mysql__max_persistent= \
    PHP__mysql__max_links= \
    PHP__mysql__trace_mode= \
    PHP__mysql__default_port= \
    PHP__mysql__default_socket= \
    PHP__mysql__default_host= \
    PHP__mysql__default_user= \
    PHP__mysql__default_password= \
    PHP__mysql__connect_timeout= \
    \
    PHP__mysqli__allow_local_infile=1 \
    PHP__mysqli__allow_persistent=1 \
    PHP__mysqli__max_persistent=-1 \
    PHP__mysqli__max_links=-1 \
    PHP__mysqli__default_port=3306 \
    PHP__mysqli__default_socket= \
    PHP__mysqli__default_host= \
    PHP__mysqli__default_user= \
    PHP__mysqli__default_pw= \
    PHP__mysqli__reconnect= \
    PHP__mysqli__cache_size= \
    \
    PHP__mysqlnd_memcache__enable= \
    PHP__mysqlnd_ms__enable= \
    PHP__mysqlnd_ms__force_config_usage= \
    PHP__mysqlnd_ms__ini_file= \
    PHP__mysqlnd_ms__config_file= \
    PHP__mysqlnd_ms__collect_statistics= \
    PHP__mysqlnd_ms__multi_master= \
    PHP__mysqlnd_ms__disable_rw_split= \
    PHP__mysqlnd_mux__enable= \
    PHP__mysqlnd_qc__enable_qc= \
    PHP__mysqlnd_qc__ttl= \
    PHP__mysqlnd_qc__cache_by_default= \
    PHP__mysqlnd_qc__cache_no_table= \
    PHP__mysqlnd_qc__use_request_time= \
    PHP__mysqlnd_qc__time_statistics= \
    PHP__mysqlnd_qc__collect_statistics= \
    PHP__mysqlnd_qc__collect_statistics_log_file= \
    PHP__mysqlnd_qc__collect_query_trace= \
    PHP__mysqlnd_qc__query_trace_bt_depth= \
    PHP__mysqlnd_qc__collect_normalized_query_trace= \
    PHP__mysqlnd_qc__ignore_sql_comments= \
    PHP__mysqlnd_qc__slam_defense= \
    PHP__mysqlnd_qc__slam_defense_ttl= \
    PHP__mysqlnd_qc__std_data_copy= \
    PHP__mysqlnd_qc__apc_prefix= \
    PHP__mysqlnd_qc__memc_server= \
    PHP__mysqlnd_qc__memc_port= \
    PHP__mysqlnd_qc__sqlite_data_file= \
    PHP__mysqlnd_uh__enable= \
    PHP__mysqlnd_uh__report_wrong_types= \
    \
    PHP__nsapi__read_timeout= \
    \
    PHP__oci8__connection_class= \
    PHP__oci8__default_prefetch= \
    PHP__oci8__events= \
    PHP__oci8__max_persistent= \
    PHP__oci8__old_oci_close_semantics= \
    PHP__oci8__persistent_timeout= \
    PHP__oci8__ping_interval= \
    PHP__oci8__privileged_connect= \
    PHP__oci8__statement_cache_size= \
    \
    PHP__odbc__allow_persistent= \
    PHP__odbc__check_persistent= \
    PHP__odbc__defaultbinmode= \
    PHP__odbc__defaultlrl= \
    PHP__odbc__default_db= \
    PHP__odbc__default_pw= \
    PHP__odbc__default_user= \
    PHP__odbc__max_links= \
    PHP__odbc__max_persistent= \
    \
    PHP__odbtp__datetime_format= \
    PHP__odbtp__detach_default_queries= \
    PHP__odbtp__guid_format= \
    PHP__odbtp__interface_file= \
    PHP__odbtp__truncation_errors= \
    \
    PHP__opcache__blacklist_filename= \
    PHP__opcache__consistency_checks=0 \
    PHP__opcache__dups_fix=0 \
    PHP__opcache__enable=1 \
    PHP__opcache__enable_cli=1 \
    PHP__opcache__enable_file_override=0 \
    PHP__opcache__error_log= \
    PHP__opcache__fast_shutdown= \
    PHP__opcache__file_update_protection=2 \
    PHP__opcache__force_restart_timeout=180 \
    PHP__opcache__inherited_hack=1 \
    PHP__opcache__interned_strings_buffer=16 \
    PHP__opcache__load_comments= \
    PHP__opcache__log_verbosity_level=1 \
    PHP__opcache__max_accelerated_files=40000 \
    PHP__opcache__max_file_size=0 \
    PHP__opcache__max_wasted_percentage=5 \
    PHP__opcache__memory_consumption=256 \
    PHP__opcache__mmap_base= \
    PHP__opcache__optimization_level=0x7FFFBFFF \
    PHP__opcache__preferred_memory_model= \
    PHP__opcache__protect_memory=0 \
    PHP__opcache__revalidate_freq=0 \
    PHP__opcache__revalidate_path=0 \
    PHP__opcache__save_comments=1 \
    PHP__opcache__use_cwd=1 \
    PHP__opcache__validate_timestamps=1 \
    \
    PHP__opendirectory__max_refs= \
    PHP__opendirectory__separator= \
    \
    PHP__pam__servicename= \
    \
    PHP__pcre__backtrack_limit=1000000 \
    PHP__pcre__recursion_limit=100000 \
    \
    PHP__pdo__dsn__*= \
    \
    PHP__pdo_odbc__connection_pooling= \
    \
    PHP__pgsql__allow_persistent= \
    PHP__pgsql__auto_reset_persistent= \
    PHP__pgsql__ignore_notice= \
    PHP__pgsql__log_notice= \
    PHP__pgsql__max_links= \
    PHP__pgsql__max_persistent= \
    \
    PHP__phar__extract_list= \
    PHP__phar__readonly=1 \
    PHP__phar__require_hash=1 \
    \
    PHP__python__append_path= \
    PHP__python__prepend_path= \
    \
    PHP__runkit__internal_override= \
    PHP__runkit__superglobal= \
    \
    PHP__session__auto_start=0 \
    PHP__session__cache_expire=180 \
    PHP__session__cache_limiter=nocache \
    PHP__session__cookie_domain= \
    PHP__session__cookie_httponly= \
    PHP__session__cookie_lifetime=0 \
    PHP__session__cookie_path=/ \
    PHP__session__cookie_secure=0 \
    PHP__session__entropy_file= \
    PHP__session__entropy_length= \
    PHP__session__gc_divisor=1000 \
    PHP__session__gc_maxlifetime=1440 \
    PHP__session__gc_probability=0 \
    PHP__session__hash_bits_per_character=6 \
    PHP__session__hash_function= \
    PHP__session__name=PHPSESSID \
    PHP__session__referer_check= \
    PHP__session__save_handler=files \
    PHP__session__save_path=/var/lib/php/sessions \
    PHP__session__serialize_handler=php \
    PHP__session__use_cookies=1 \
    PHP__session__use_only_cookies=1 \
    PHP__session__use_trans_sid=0 \
    \
    PHP__session_pgsql__create_table= \
    PHP__session_pgsql__db= \
    PHP__session_pgsql__disable= \
    PHP__session_pgsql__failover_mode= \
    PHP__session_pgsql__gc_interval= \
    PHP__session_pgsql__keep_expired= \
    PHP__session_pgsql__sem_file_name= \
    PHP__session_pgsql__serializable= \
    PHP__session_pgsql__short_circuit= \
    PHP__session_pgsql__use_app_vars= \
    PHP__session_pgsql__vacuum_interval= \
    \
    PHP__simple_cvs__authMethod= \
    PHP__simple_cvs__compressionLevel= \
    PHP__simple_cvs__cvsRoot= \
    PHP__simple_cvs__host= \
    PHP__simple_cvs__moduleName= \
    PHP__simple_cvs__userName= \
    PHP__simple_cvs__workingDir= \
    \
    PHP__soap__wsdl_cache=1 \
    PHP__soap__wsdl_cache_dir=/tmp \
    PHP__soap__wsdl_cache_enabled=1 \
    PHP__soap__wsdl_cache_limit=86400 \
    PHP__soap__wsdl_cache_ttl=5 \
    \
    PHP__sql__safe_mode= \
    \
    PHP__sqlite__assoc_case= \
    \
    PHP__sybase__allow_persistent= \
    PHP__sybase__interface_file= \
    PHP__sybase__max_links= \
    PHP__sybase__max_persistent= \
    PHP__sybase__min_error_severity= \
    PHP__sybase__min_message_severity= \
    \
    PHP__sybct__deadlock_retry_count= \
    PHP__sybct__login_timeout= \
    PHP__sybct__packet_size= \
    PHP__sybct__timeout= \
    \
    PHP__sysvshm__init_mem= \
    \
    PHP__tidy__clean_output= \
    PHP__tidy__default_config= \
    \
    PHP__uploadprogress__file__filename_template= \
    \
    PHP__url_rewriter__tags="form=" \
    \
    PHP__user_ini__cache_ttl=300 \
    PHP__user_ini__filename=.user.ini \
    \
    PHP__valkyrie__auto_validate= \
    PHP__valkyrie__config_path= \
    \
    PHP__vld__active= \
    PHP__vld__execute= \
    PHP__vld__skip_append= \
    PHP__vld__skip_prepend= \
    \
    PHP__xmms__path= \
    PHP__xmms__session= \
    \
    PHP__yami__response__timeout= \
    \
    PHP__yaz__keepalive= \
    PHP__yaz__log_mask= \
    \
    PHP__zend__enable_gc=1 \
    PHP__zend__multibyte=0 \
    PHP__zend__script_encoding= \
    PHP__zend__signal_check=0 \
    \
    PHP__zlib__output_compression= \
    PHP__zlib__output_compression_level=-1 \
    PHP__zlib__output_handler= \
    \
    PHP__xdebug__auto_trace=Off \
    PHP__xdebug__cli_color=0 \
    PHP__xdebug__collect_assignments=Off \
    PHP__xdebug__collect_includes=On \
    PHP__xdebug__collect_params=0 \
    PHP__xdebug__collect_return=Off \
    PHP__xdebug__collect_vars=Off \
    PHP__xdebug__coverage_enable=On \
    PHP__xdebug__default_enable=On \
    PHP__xdebug__dump__COOKIE= \
    PHP__xdebug__dump__ENV= \
    PHP__xdebug__dump__FILES= \
    PHP__xdebug__dump__GET= \
    PHP__xdebug__dump__POST= \
    PHP__xdebug__dump__REQUEST= \
    PHP__xdebug__dump__SERVER= \
    PHP__xdebug__dump__SESSION= \
    PHP__xdebug__dump_globals=On \
    PHP__xdebug__dump_once=On \
    PHP__xdebug__dump_undefined=Off \
    PHP__xdebug__extended_info=On \
    PHP__xdebug__file_link_format= \
    PHP__xdebug__filename_format= \
    PHP__xdebug__force_display_errors=Off \
    PHP__xdebug__force_error_reporting=0 \
    PHP__xdebug__gc_stats_enable=Off \
    PHP__xdebug__gc_stats_output_dir=/tmp \
    PHP__xdebug__gc_stats_output_name=gcstats.%p \
    PHP__xdebug__halt_level=0 \
    PHP__xdebug__idekey= \
    PHP__xdebug__max_nesting_level=256 \
    PHP__xdebug__max_stack_frames=-1 \
    PHP__xdebug__overload_var_dump=2 \
    PHP__xdebug__profiler_aggregate=Off \
    PHP__xdebug__profiler_append=Off \
    PHP__xdebug__profiler_enable=Off \
    PHP__xdebug__profiler_enable_trigger=Off \
    PHP__xdebug__profiler_enable_trigger_value= \
    PHP__xdebug__profiler_output_dir=/tmp \
    PHP__xdebug__profiler_output_name=cachegrind.out.%p \
    PHP__xdebug__remote_addr_header= \
    PHP__xdebug__remote_autostart=On \
    PHP__xdebug__remote_connect_back=Off \
    PHP__xdebug__remote_cookie_expire_time=3600 \
    PHP__xdebug__remote_enable=On \
    PHP__xdebug__remote_handler=dbgp \
    PHP__xdebug__remote_host=host.docker.internal \
    PHP__xdebug__remote_log= \
    PHP__xdebug__remote_mode=req \
    PHP__xdebug__remote_port=9000 \
    PHP__xdebug__remote_timeout=200 \
    PHP__xdebug__scream=Off \
    PHP__xdebug__show_error_trace=Off \
    PHP__xdebug__show_exception_trace=Off \
    PHP__xdebug__show_local_vars=Off \
    PHP__xdebug__show_mem_delta=Off \
    PHP__xdebug__trace_enable_trigger=Off \
    PHP__xdebug__trace_enable_trigger_value= \
    PHP__xdebug__trace_format=0 \
    PHP__xdebug__trace_options=0 \
    PHP__xdebug__trace_output_dir=/tmp \
    PHP__xdebug__trace_output_name=trace.%c \
    PHP__xdebug__var_display_max_children=128 \
    PHP__xdebug__var_display_max_data=512 \
    PHP__xdebug__var_display_max_depth=3 \
    \
    FPM__access__format="%R - %u %t \"%m %r\" %s" \
    FPM__listen="0.0.0.0:9000" \
    FPM__listen__backlog=511 \
    FPM__listen__mode=0660 \
    FPM__pid="/var/run/php-fpm/php-fpm.pid" \
    FPM__pm=dynamic \
    FPM__pm__max_children=5 \
    FPM__pm__start_servers=2 \
    FPM__pm__min_spare_servers=1 \
    FPM__pm__max_spare_servers=3 \
    FPM__pm__process_idle_timeout=10s \
    FPM__pm__max_requests=0 \
    FPM__security__limit_extensions=.php \
