#!/usr/bin/env bash

# env PHPFPM_XDEBUG must be "On" or "on" to enable Xdebug support
# Otherwise this is strictly disabled by default
PHPFPM_XDEBUG=${PHPFPM_XDEBUG:-""}
MATCH=On
if [ "${PHPFPM_XDEBUG,,}" = "${MATCH,,}" ]; then
    PHPFPM_XDEBUG=on
else
    PHPFPM_XDEBUG=off
fi

exec nginx -g "daemon off; env PHPFPM_XDEBUG=${PHPFPM_XDEBUG};"
