#!/usr/bin/env bash

# env PHPFPM_XDEBUG must be "On" or "on" to enable Xdebug support
# Otherwise this is strictly disabled by default
PHPFPM_XDEBUG=${PHPFPM_XDEBUG:-""}
if [[ "${PHPFPM_XDEBUG,,}" = "on" ]]; then
    PHPFPM_XDEBUG_PORT=9999
else
    PHPFPM_XDEBUG_PORT=9000
fi

# If default vhost file does not exist, use env var VHOST to choose
if [[ ! -f /etc/nginx/sites-enabled/default ]]; then
    VHOST=${VHOST:-"fpm"}
    if [[ ${VHOST} != *".conf"* ]]; then
        VHOST=${VHOST}.conf
    fi

    echo Using /etc/nginx/sites-available/${VHOST}

    ln -s /etc/nginx/sites-available/${VHOST} /etc/nginx/sites-enabled/default
fi

exec nginx -g "daemon off; env PHPFPM_XDEBUG_PORT=${PHPFPM_XDEBUG_PORT};"
