#!/usr/bin/env bash
set -e
set -o pipefail

docker image build \
    -t jtreminio/phpenv-cli:latest \
    -f Dockerfile-cli-env \
    ./../

PHP73="7.3.3"
docker image build \
  -t jtreminio/php:7.3-cli \
  -t jtreminio/php:${PHP73}-cli \
  -f Dockerfile-cli-7.3 \
  ./../

PHP72="7.2.16"
docker image build \
  --build-arg PHP_VER_DOT=${PHP72} \
  -t jtreminio/php:7.2-cli \
  -t jtreminio/php:${PHP72}-cli \
  -f Dockerfile-cli-7.2 \
  ./../

PHP71="7.1.27"
docker image build \
  --build-arg PHP_VER_DOT=${PHP71} \
  -t jtreminio/php:7.1-cli \
  -t jtreminio/php:${PHP71}-cli \
  -f Dockerfile-cli-7.1 \
  ./../

PHP70="7.0.33"
docker image build \
  --build-arg PHP_VER_DOT=${PHP70} \
  -t jtreminio/php:7.0-cli \
  -t jtreminio/php:${PHP70}-cli \
  -f Dockerfile-cli-7.0 \
  ./../

PHP56="5.6.40"
docker image build \
  --build-arg PHP_VER_DOT=${PHP56} \
  -t jtreminio/php:5.6-cli \
  -t jtreminio/php:${PHP56}-cli \
  -f Dockerfile-cli-5.6 \
  ./../

cat << EOF
Push to Docker Hub with:

docker image push jtreminio/phpenv-cli:latest

docker image push jtreminio/php:7.3-cli
docker image push jtreminio/php:${PHP73}-cli

docker image push jtreminio/php:7.2-cli
docker image push jtreminio/php:${PHP72}-cli

docker image push jtreminio/php:7.1-cli
docker image push jtreminio/php:${PHP71}-cli

docker image push jtreminio/php:7.0-cli
docker image push jtreminio/php:${PHP70}-cli

docker image push jtreminio/php:5.6-cli
docker image push jtreminio/php:${PHP56}-cli
EOF
