FROM jtreminio/php:7.1
LABEL maintainer="Juan Treminio <jtreminio@gmail.com>"

RUN apt-get update &&\
    apt-get install --no-install-recommends --no-install-suggests -y \
        supervisor \
        nginx &&\
    apt-get -y --purge autoremove &&\
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \
           /usr/lib/x86_64-linux-gnu/perl /usr/share/perl \
           /usr/lib/x86_64-linux-gnu/libperl.* /usr/share/{man,doc}

# Set proper permissions and symlink log files for Nginx
RUN chown -R www-data:www-data /var/lib/nginx &&\
    install -d -m 0755 -o www-data -g www-data \
        /var/cache/nginx \
        /var/run/nginx &&\
    touch \
        /var/log/nginx/access.log \
        /var/log/nginx/error.log &&\
    chown -R www-data:www-data \
        /var/log/nginx/access.log \
        /var/log/nginx/error.log \
        /var/www &&\
    rm -rf /var/www/html

COPY files/supervisord.conf /etc/supervisor/conf.d/supervisord.conf
COPY files/nginx.conf       /etc/nginx/nginx.conf
COPY files/vhost.conf       /etc/nginx/sites-available/default

EXPOSE 8080

# Start with
# /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
