FROM jtreminio/php:7.3
LABEL maintainer="Juan Treminio <jtreminio@gmail.com>"

RUN apt-get update &&\
    apt-get install --no-install-recommends --no-install-suggests -y \
        nginx &&\
    apt-get -y --purge autoremove &&\
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \
           /usr/lib/x86_64-linux-gnu/perl /usr/share/perl \
           /usr/lib/x86_64-linux-gnu/libperl.* /usr/share/{man,doc}

# Set proper permissions for Nginx
RUN chown -R www-data:www-data \
        /var/lib/nginx \
        /var/www &&\
    install -d -m 0755 -o www-data -g www-data \
        /var/cache/nginx \
        /var/run/nginx &&\
    rm -rf /var/www/html

COPY files/nginx.conf /etc/nginx/nginx.conf
COPY files/vhost.conf /etc/nginx/sites-available/default

# runit config
RUN mkdir /etc/service/nginx
COPY files/nginx /etc/service/nginx/run
RUN chmod +x /etc/service/nginx/run

# Replace 0.0.0.0:9000
ENV FPM.listen="127.0.0.1:9000"

EXPOSE 8080

CMD ["/sbin/my_init"]
