#!/usr/bin/env bash

PHP_INI_SCAN_DIR=${PHP_INI_SCAN_DIR:-":/etc/php/fpm-conf.d/"}

exec /usr/sbin/php-fpm \
            -c ${PHP_INI_SCAN_DIR} \
            --nodaemonize \
            --force-stderr 2>&1 | \
        sed -u 's,.*: \"\(.*\)$,\1,'| \
        sed -u 's,"$,,' 1>&1
