#!/usr/bin/env bash

PHP_INI_SCAN_DIR=${PHP_INI_SCAN_DIR:""}
# Prevent defining xdebug INI location twice
if [[ ${PHP_INI_SCAN_DIR} != *"xdebug"* ]]; then
    PHP_INI_SCAN_DIR=${PHP_INI_SCAN_DIR}:/p/xdebug
fi

PHP_INI_SCAN_DIR=${PHP_INI_SCAN_DIR} \
XDEBUG_CONFIG="idekey=xdebug" php -dxdebug.remote_enable=1 "$@"
