#!/usr/bin/env bash
set -e
set -o pipefail

# 7.3
docker image build \
  -t jtreminio/php-apache:7.3 \
  -f Dockerfile-apache-7.3 \
  .

# 7.2
docker image build \
  -t jtreminio/php-apache:7.2 \
  -f Dockerfile-apache-7.2 \
  .

# 7.1
docker image build \
  -t jtreminio/php-apache:7.1 \
  -f Dockerfile-apache-7.1 \
  .

# 7.0
docker image build \
  -t jtreminio/php-apache:7.0 \
  -f Dockerfile-apache-7.0 \
  .

# 5.6
docker image build \
  -t jtreminio/php-apache:5.6 \
  -f Dockerfile-apache-5.6 \
  .

cat << EOF
Push to Docker Hub with:

docker image push jtreminio/php-apache:7.3

docker image push jtreminio/php-apache:7.2

docker image push jtreminio/php-apache:7.1

docker image push jtreminio/php-apache:7.0

docker image push jtreminio/php-apache:5.6

Pull with:

docker image pull jtreminio/php-apache:7.3

docker image pull jtreminio/php-apache:7.2

docker image pull jtreminio/php-apache:7.1

docker image pull jtreminio/php-apache:7.0

docker image pull jtreminio/php-apache:5.6
EOF
