#!/usr/bin/env bash

# env PHPFPM_XDEBUG must be "On" or "on" to enable Xdebug support
# Otherwise this is strictly disabled by default
PHPFPM_XDEBUG=${PHPFPM_XDEBUG:-""}
if [[ "${PHPFPM_XDEBUG,,}" = "on" ]]; then
    PHPFPM_XDEBUG_PORT=9999
else
    PHPFPM_XDEBUG_PORT=9000
fi

export PHPFPM_XDEBUG_PORT

# If default vhost file does not exist, use env var VHOST to choose
if [[ ! -f /etc/apache2/sites-enabled/default.conf ]]; then
    VHOST=${VHOST:-"fpm"}
    if [[ ${VHOST} != *".conf"* ]]; then
        VHOST=${VHOST}.conf
    fi

    echo Using /etc/apache2/sites-available/${VHOST}

    ln -s /etc/apache2/sites-available/${VHOST} /etc/apache2/sites-enabled/default.conf
fi

exec /usr/sbin/apache2ctl -D FOREGROUND
